# Generated by Django 5.0.3 on 2024-05-05 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstock',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color'),
        ),
    ]
