# Generated by Django 5.0.3 on 2024-07-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_itemstock_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoric',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
